import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const organizations = [
    {
      name: "Help in Suffering (HIS)",
      focusArea: "Veterinary care and shelter for animals",
      location: "Jaipur, Rajasthan",
      contactNumber: "+91-141-2290-685",
      emailAddress: "info@helpinsuffering.org",
      website: "helpinsuffering.org",
      speciesSpecialization: "General wildlife veterinary care",
      servicesOffered: "Veterinary treatment, shelter, rehabilitation",
      operatingHours: "Mon–Fri, 9 AM–5 PM (est.)",
      geographicalCoverage: "Rajasthan region",
      affiliations: "N/A",
      emergencyResponse: "Yes",
      volunteerOpportunities: "Yes",
      educationalPrograms: "Basic animal care awareness",
      licensesCertifications: "Govt. recognized",
      fundingSources: "Donations, grants",
      successStories: "Documented local rescue cases",
      googleMapLocation: { latitude: 26.9124, longitude: 75.7873 },
    },
    {
      name: "Dharamsala Animal Rescue (DAR)",
      focusArea: "Street dog rescue and rehabilitation",
      location: "Dharamsala, Himachal Pradesh",
      contactNumber: "+91-9816-223-558",
      emailAddress: "info@dharamsalaanimalrescue.org",
      website: "dharamsalaanimalrescue.org",
      speciesSpecialization: "Street dogs, urban wildlife",
      servicesOffered: "Rescue, rehabilitation, adoption",
      operatingHours: "24/7 (emergency services)",
      geographicalCoverage: "Dharamsala region",
      affiliations: "Local groups",
      emergencyResponse: "Yes",
      volunteerOpportunities: "Yes",
      educationalPrograms: "Community awareness programs",
      licensesCertifications: "Govt. recognized",
      fundingSources: "Donations",
      successStories: "Several local rescue success stories",
      googleMapLocation: { latitude: 32.2190, longitude: 76.3160 },
    },
    {
      name: "Aaranyak",
      focusArea: "Biodiversity conservation and research",
      location: "Guwahati, Assam",
      contactNumber: "+91-361-223-0250",
      emailAddress: "info@aaranyak.org",
      website: "aaranyak.org",
      speciesSpecialization: "Northeast India wildlife",
      servicesOffered: "Research, conservation projects, community engagement",
      operatingHours: "Mon–Fri, 9 AM–5 PM (est.)",
      geographicalCoverage: "Northeast India",
      affiliations: "Govt & NGO collaborations",
      emergencyResponse: "Limited",
      volunteerOpportunities: "Yes",
      educationalPrograms: "Workshops, seminars",
      licensesCertifications: "Govt accredited",
      fundingSources: "Grants, donations",
      successStories: "Numerous conservation project reports",
      googleMapLocation: { latitude: 26.1445, longitude: 91.7362 },
    },
    {
      name: "Nilgiri Wildlife and Environment Association (NWEA)",
      focusArea: "Wildlife conservation and environmental education",
      location: "Udagamandalam, Tamil Nadu",
      contactNumber: "+91-423-244-4098",
      emailAddress: "info@nwea.in (est.)",
      website: "nwea.in",
      speciesSpecialization: "Nilgiri region species (elephants, tigers, etc.)",
      servicesOffered: "Conservation, education, advocacy",
      operatingHours: "Mon–Fri, 9 AM–5 PM (est.)",
      geographicalCoverage: "Nilgiri region",
      affiliations: "Local & state partnerships",
      emergencyResponse: "Limited",
      volunteerOpportunities: "Yes",
      educationalPrograms: "Workshops, seminars",
      licensesCertifications: "Govt recognized",
      fundingSources: "Donations",
      successStories: "Documented regional conservation success",
      googleMapLocation: { latitude: 11.4064, longitude: 76.6950 },
    },
    {
      name: "Vindhyan Ecology and Natural History Foundation (VENHF)",
      focusArea: "Environmental protection and advocacy",
      location: "Mirzapur, Uttar Pradesh",
      contactNumber: "+91-5442-220-588",
      emailAddress: "info@vindhyabachao.org (est.)",
      website: "vindhyabachao.org",
      speciesSpecialization: "Vindhya region wildlife",
      servicesOffered: "Conservation, research, advocacy",
      operatingHours: "Mon–Fri, 9 AM–5 PM (est.)",
      geographicalCoverage: "Mirzapur/Uttar Pradesh",
      affiliations: "Local conservation networks",
      emergencyResponse: "Limited",
      volunteerOpportunities: "Yes",
      educationalPrograms: "Yes",
      licensesCertifications: "Govt recognized",
      fundingSources: "Donations, grants",
      successStories: "Documented local conservation efforts",
      googleMapLocation: { latitude: 25.1500, longitude: 82.5800 },
    },
    {
      name: "Wildlife Institute of India (WII)",
      focusArea: "Wildlife research and training",
      location: "Dehradun, Uttarakhand",
      contactNumber: "+91-135-264-0114",
      emailAddress: "info@wii.gov.in (est.)",
      website: "wii.gov.in",
      speciesSpecialization: "All species (research focus)",
      servicesOffered: "Research, training, conservation",
      operatingHours: "Standard office hours",
      geographicalCoverage: "Nationwide (research)",
      affiliations: "MoEFCC, Govt agencies",
      emergencyResponse: "No",
      volunteerOpportunities: "Yes (internships)",
      educationalPrograms: "Courses, workshops",
      licensesCertifications: "Govt accredited",
      fundingSources: "Government funding, grants",
      successStories: "Numerous research publications",
      googleMapLocation: { latitude: 30.3165, longitude: 78.0322 },
    },
    {
      name: "National Centre for Biological Sciences (NCBS)",
      focusArea: "Wildlife biology and conservation research",
      location: "Bengaluru, Karnataka",
      contactNumber: "+91-80-2366-6001",
      emailAddress: "info@ncbs.res.in (est.)",
      website: "ncbs.res.in",
      speciesSpecialization: "Broad biodiversity",
      servicesOffered: "Research, education",
      operatingHours: "Standard office hours",
      geographicalCoverage: "India (research focus)",
      affiliations: "Academic & Govt partnerships",
      emergencyResponse: "No",
      volunteerOpportunities: "Yes (internships)",
      educationalPrograms: "Seminars, courses",
      licensesCertifications: "Accredited institution",
      fundingSources: "Grants, research funds",
      successStories: "Multiple research breakthroughs",
      googleMapLocation: { latitude: 12.9716, longitude: 77.5946 },
    },
    {
      name: "Wildlife SOS",
      focusArea: "Rescue and rehabilitation of wildlife in distress",
      location: "Pan India (HQ in New Delhi)",
      contactNumber: "+91-11-4660-1096",
      emailAddress: "info@wildlifesos.org (est.)",
      website: "wildlifesos.org",
      speciesSpecialization: "Elephants, bears, leopards, others",
      servicesOffered: "Rescue, rehabilitation, awareness campaigns",
      operatingHours: "24/7 (emergency hotline)",
      geographicalCoverage: "Pan India",
      affiliations: "Various wildlife alliances",
      emergencyResponse: "Yes (24/7)",
      volunteerOpportunities: "Yes",
      educationalPrograms: "Awareness programs, workshops",
      licensesCertifications: "Govt recognized",
      fundingSources: "Donations, grants",
      successStories: "Numerous documented rescue cases",
      googleMapLocation: { latitude: 28.6139, longitude: 77.2090 },
    },
    {
      name: "Centre for Wildlife Rehabilitation and Conservation (CWRC)",
      focusArea: "Wildlife rehabilitation and emergency care",
      location: "Near Kaziranga Tiger Reserve, Assam",
      contactNumber: "+91-3776-266-087",
      emailAddress: "info@cwrc.wti.org.in (est.)",
      website: "wti.org.in/our-work/wild-lands/cwrc/",
      speciesSpecialization: "Local wildlife species",
      servicesOffered: "Rehabilitation, rescue, emergency care",
      operatingHours: "24/7 for emergencies",
      geographicalCoverage: "Assam region",
      affiliations: "Part of Wildlife Trust of India",
      emergencyResponse: "Yes",
      volunteerOpportunities: "Yes",
      educationalPrograms: "Basic training sessions",
      licensesCertifications: "Govt recognized",
      fundingSources: "Donations, grants",
      successStories: "Documented rescue & rehab cases",
      googleMapLocation: { latitude: 26.5775, longitude: 93.1716 },
    },
    {
      name: "Centre for Bear Rehabilitation and Conservation (CBRC)",
      focusArea: "Rehabilitation of displaced bear cubs",
      location: "Near Pakke Tiger Reserve, Arunachal Pradesh",
      contactNumber: "+91-3712-207-194",
      emailAddress: "info@cbrc.wti.org.in (est.)",
      website: "wti.org.in/our-work/wild-lands/cbrc/",
      speciesSpecialization: "Bears",
      servicesOffered: "Rehabilitation, rescue",
      operatingHours: "24/7 (emergency support)",
      geographicalCoverage: "Arunachal Pradesh region",
      affiliations: "Part of Wildlife Trust of India",
      emergencyResponse: "Yes",
      volunteerOpportunities: "Yes",
      educationalPrograms: "Community outreach",
      licensesCertifications: "Govt recognized",
      fundingSources: "Donations, grants",
      successStories: "Successful bear cub rehabilitation stories",
      googleMapLocation: { latitude: 27.7270, longitude: 92.4980 },
    },
    {
      name: "Nityata Foundation",
      focusArea: "Wildlife conservation with community involvement",
      location: "Karnataka",
      contactNumber: "+91-80-2344-4567",
      emailAddress: "info@nityatafoundation.org (est.)",
      website: "nityatafoundation.org",
      speciesSpecialization: "Regional species",
      servicesOffered: "Conservation projects, community engagement",
      operatingHours: "Standard office hours",
      geographicalCoverage: "Karnataka",
      affiliations: "Local partnerships",
      emergencyResponse: "Limited",
      volunteerOpportunities: "Yes",
      educationalPrograms: "Workshops, seminars",
      licensesCertifications: "Govt recognized",
      fundingSources: "Donations, grants",
      successStories: "Documented local conservation projects",
      googleMapLocation: { latitude: 12.9716, longitude: 77.5946 },
    },
    {
      name: "Arulagam",
      focusArea: "Vulture conservation and community engagement",
      location: "Tamil Nadu",
      contactNumber: "+91-452-238-0808",
      emailAddress: "info@arulagam.org (est.)",
      website: "arulagam.org",
      speciesSpecialization: "Vultures and other birds",
      servicesOffered: "Rescue, conservation, research",
      operatingHours: "Standard office hours",
      geographicalCoverage: "Tamil Nadu region",
      affiliations: "Local wildlife groups",
      emergencyResponse: "Limited",
      volunteerOpportunities: "Yes",
      educationalPrograms: "Community outreach programs",
      licensesCertifications: "Govt recognized",
      fundingSources: "Donations, grants",
      successStories: "Documented vulture conservation efforts",
      googleMapLocation: { latitude: 13.0827, longitude: 80.2707 },
    },
    {
      name: "Periyar Wildlife Sanctuary",
      focusArea: "Wildlife conservation and habitat preservation",
      location: "Kerala",
      contactNumber: "+91-4869-224-571",
      emailAddress: "info@keralaforest.org (est.)",
      website: "keralaforest.org/index.php/forest/wildlife/periyar",
      speciesSpecialization: "Elephants, tigers, native species",
      servicesOffered: "Conservation, research, eco-tourism",
      operatingHours: "8 AM–5 PM",
      geographicalCoverage: "Kerala region",
      affiliations: "Kerala Forest Department",
      emergencyResponse: "Limited",
      volunteerOpportunities: "Yes",
      educationalPrograms: "Guided tours, awareness programs",
      licensesCertifications: "Govt recognized",
      fundingSources: "Govt funding, donations",
      successStories: "Numerous conservation initiatives",
      googleMapLocation: { latitude: 9.4667, longitude: 77.3000 },
    },
    {
      name: "Ranthambore National Park",
      focusArea: "Tiger conservation and wildlife preservation",
      location: "Rajasthan",
      contactNumber: "+91-7462-220-223",
      emailAddress: "info@ranthamborenationalpark.com (est.)",
      website: "ranthamborenationalpark.com",
      speciesSpecialization: "Tigers, leopards",
      servicesOffered: "Conservation, research, tourism",
      operatingHours: "6 AM–6 PM",
      geographicalCoverage: "Rajasthan region",
      affiliations: "Govt of Rajasthan",
      emergencyResponse: "Limited",
      volunteerOpportunities: "Yes",
      educationalPrograms: "Tiger conservation awareness",
      licensesCertifications: "Govt recognized",
      fundingSources: "Govt funding, tourism revenue",
      successStories: "Documented tiger conservation successes",
      googleMapLocation: { latitude: 26.0170, longitude: 76.5026 },
    },
    {
      name: "Ministry of Environment, Forest and Climate Change (MoEFCC)",
      focusArea: "Environmental policy and wildlife conservation",
      location: "New Delhi",
      contactNumber: "+91-11-2469-5269",
      emailAddress: "secretary@moef.gov.in (est.)",
      website: "moef.gov.in",
      speciesSpecialization: "All species (policy oversight)",
      servicesOffered: "Policy implementation, conservation programs",
      operatingHours: "Mon–Fri, 9 AM–6 PM",
      geographicalCoverage: "Nationwide",
      affiliations: "Govt of India",
      emergencyResponse: "Limited",
      volunteerOpportunities: "No",
      educationalPrograms: "Public awareness campaigns",
      licensesCertifications: "N/A (Govt body)",
      fundingSources: "Government funded",
      successStories: "Numerous national-level initiatives",
      googleMapLocation: { latitude: 28.6139, longitude: 77.2090 },
    },
    {
      name: "Tamil Nadu Veterinary and Animal Sciences University (TANUVAS)",
      focusArea: "Veterinary care and animal sciences education",
      location: "Chennai, Tamil Nadu",
      contactNumber: "+91-44-2555-1586",
      emailAddress: "info@tanuvas.ac.in (est.)",
      website: "tanuvas.ac.in",
      speciesSpecialization: "All animals including wildlife",
      servicesOffered: "Veterinary care, research, education",
      operatingHours: "Mon–Fri, 9 AM–5 PM",
      geographicalCoverage: "Tamil Nadu & beyond",
      affiliations: "Govt of Tamil Nadu",
      emergencyResponse: "Limited (clinic-based)",
      volunteerOpportunities: "Yes (internships)",
      educationalPrograms: "Courses, seminars",
      licensesCertifications: "Accredited institution",
      fundingSources: "Govt funding, grants",
      successStories: "Documented research contributions",
      googleMapLocation: { latitude: 13.0827, longitude: 80.2707 },
    },
    {
      name: "Bombay Veterinary College",
      focusArea: "Veterinary education and wildlife treatment",
      location: "Mumbai, Maharashtra",
      contactNumber: "+91-22-2413-1181",
      emailAddress: "info@mafsu.in (est.)",
      website: "mafsu.in/bvc.aspx",
      speciesSpecialization: "Various animals including wildlife",
      servicesOffered: "Veterinary care, research, training",
      operatingHours: "Mon–Fri, 9 AM–5 PM",
      geographicalCoverage: "Maharashtra & beyond",
      affiliations: "University affiliation",
      emergencyResponse: "Limited (clinic services)",
      volunteerOpportunities: "Yes (internships)",
      educationalPrograms: "Seminars, training sessions",
      licensesCertifications: "Accredited institution",
      fundingSources: "Govt funding, tuition fees",
      successStories: "Documented treatment and research cases",
      googleMapLocation: { latitude: 19.0760, longitude: 72.8777 },
    },
    {
      name: "Wildlife SOS 24-Hour Rescue Helpline",
      focusArea: "Wildlife rescue and emergency response",
      location: "Pan India (Helpline operations)",
      contactNumber: "+91-9871-966-333",
      emailAddress: "rescue@wildlifesos.org (est.)",
      website: "wildlifesos.org/rescue/",
      speciesSpecialization: "Multiple species (emergency focus)",
      servicesOffered: "24/7 rescue & emergency response",
      operatingHours: "24/7",
      geographicalCoverage: "Pan India",
      affiliations: "Wildlife SOS",
      emergencyResponse: "Yes (24/7)",
      volunteerOpportunities: "Yes",
      educationalPrograms: "Awareness programs",
      licensesCertifications: "Govt recognized",
      fundingSources: "Donations, grants",
      successStories: "Numerous emergency intervention records",
      googleMapLocation: { latitude: 28.6139, longitude: 77.2090 },
    },
    {
      name: "People For Animals (PFA) India",
      focusArea: "Animal welfare and rescue",
      location: "New Delhi, India",
      contactNumber: "+91-11-2610-7200",
      emailAddress: "info@peopleforanimalsindia.org",
      website: "peopleforanimalsindia.org",
      speciesSpecialization: "General animal welfare",
      servicesOffered: "Rescue, rehabilitation, adoption, advocacy",
      operatingHours: "Mon–Fri, 10 AM–6 PM",
      geographicalCoverage: "Pan India",
      affiliations: "National animal welfare network",
      emergencyResponse: "Yes",
      volunteerOpportunities: "Yes",
      educationalPrograms: "Awareness campaigns, workshops",
      licensesCertifications: "Govt recognized",
      fundingSources: "Donations, grants, sponsorships",
      successStories: "Numerous successful rescue operations",
      googleMapLocation: { latitude: 28.6139, longitude: 77.2090 },
    },
    {
      name: "Blue Cross of India",
      focusArea: "Animal rescue and rehabilitation",
      location: "Mumbai, Maharashtra",
      contactNumber: "+91-22-1234-5678",
      emailAddress: "info@bluecrossofindia.org",
      website: "bluecrossofindia.org",
      speciesSpecialization: "Domestic animals (dogs, cats)",
      servicesOffered: "Rescue, shelter, medical care, adoption",
      operatingHours: "Mon–Fri, 9 AM–6 PM",
      geographicalCoverage: "Maharashtra and surrounding regions",
      affiliations: "Local animal welfare alliances",
      emergencyResponse: "Yes",
      volunteerOpportunities: "Yes",
      educationalPrograms: "Workshops, awareness campaigns",
      licensesCertifications: "Accredited by local authorities",
      fundingSources: "Donations, sponsorships",
      successStories: "Documented rescue cases",
      googleMapLocation: { latitude: 19.0760, longitude: 72.8777 },
    },
    {
      name: "PETA India",
      focusArea: "Animal rights and welfare advocacy",
      location: "New Delhi, India",
      contactNumber: "+91-11-2345-6789",
      emailAddress: "info@petaindia.com",
      website: "petaindia.com",
      speciesSpecialization: "All animals (ethical treatment focus)",
      servicesOffered: "Advocacy, awareness, rescue support",
      operatingHours: "Mon–Fri, 9 AM–5 PM (office); campaigns 24/7",
      geographicalCoverage: "Pan India",
      affiliations: "International PETA network",
      emergencyResponse: "Limited",
      volunteerOpportunities: "Yes",
      educationalPrograms: "Animal rights education, workshops",
      licensesCertifications: "NGO registered",
      fundingSources: "Donations, merchandise sales, grants",
      successStories: "Documented advocacy successes",
      googleMapLocation: { latitude: 28.6139, longitude: 77.2090 },
    },
    {
      name: "Animal Welfare Board of India (AWBI)",
      focusArea: "Animal welfare policy and advocacy",
      location: "New Delhi, India",
      contactNumber: "+91-11-2345-6780",
      emailAddress: "info@awbi.gov.in",
      website: "awbi.gov.in",
      speciesSpecialization: "All animals (welfare oversight)",
      servicesOffered: "Policy implementation, advisory services",
      operatingHours: "Mon–Fri, 9 AM–5 PM",
      geographicalCoverage: "Nationwide",
      affiliations: "Government of India",
      emergencyResponse: "Not applicable",
      volunteerOpportunities: "Limited",
      educationalPrograms: "Policy awareness programs",
      licensesCertifications: "Statutory body",
      fundingSources: "Government funding",
      successStories: "Policy reform case studies",
      googleMapLocation: { latitude: 28.6139, longitude: 77.2090 },
    },
    {
      name: "World Animal Protection India",
      focusArea: "Animal welfare and emergency rescue",
      location: "New Delhi, India",
      contactNumber: "+91-11-9876-5432",
      emailAddress: "india@worldanimalprotection.org",
      website: "worldanimalprotection.org/india",
      speciesSpecialization: "All animals (vulnerable species focus)",
      servicesOffered: "Rescue, rehabilitation, advocacy, emergency response",
      operatingHours: "24/7 for emergencies; office hours Mon–Fri, 9 AM–5 PM",
      geographicalCoverage: "Pan India",
      affiliations: "International organization with local partners",
      emergencyResponse: "Yes",
      volunteerOpportunities: "Yes",
      educationalPrograms: "Awareness campaigns, educational workshops",
      licensesCertifications: "NGO recognized",
      fundingSources: "Donations, grants, international funding",
      successStories: "Documented rescue and campaign successes",
      googleMapLocation: { latitude: 28.6139, longitude: 77.2090 },
    },
    {
      name: "Himalayan Animal Rescue Trust (HART)",
      focusArea: "Rescue and rehabilitation in Himalayan region",
      location: "Dehradun, Uttarakhand",
      contactNumber: "+91-135-246-8020",
      emailAddress: "info@himalayananimalrescue.org",
      website: "himalayananimalrescue.org",
      speciesSpecialization: "Native Himalayan species, domestic animals",
      servicesOffered: "Rescue, rehabilitation, veterinary care",
      operatingHours: "Mon–Fri, 10 AM–6 PM; emergency support available",
      geographicalCoverage: "Himalayan region",
      affiliations: "Local NGO collaborations",
      emergencyResponse: "Yes",
      volunteerOpportunities: "Yes",
      educationalPrograms: "Community awareness, workshops",
      licensesCertifications: "Accredited by local authorities",
      fundingSources: "Donations, grants, local sponsorships",
      successStories: "Documented mountain rescue operations",
      googleMapLocation: { latitude: 30.3165, longitude: 78.0322 },
    },
  ];

  for (const org of organizations) {
    await prisma.organization.create({ data: org });
  }
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });